export interface Definition {
  id: number;
  term: string;
  definition: string;
  category: string;
  categoryId: number;
}

export const allDefinitions: Definition[] = [
  // Cardiovascular System (30 definitions)
  { id: 1, term: "Atrium", definition: "Upper chamber of the heart that receives blood from veins", category: "Cardiovascular System", categoryId: 1 },
  { id: 2, term: "Ventricle", definition: "Lower chamber of the heart that pumps blood to arteries", category: "Cardiovascular System", categoryId: 1 },
  { id: 3, term: "Aorta", definition: "The largest artery in the body, carrying oxygenated blood from the heart", category: "Cardiovascular System", categoryId: 1 },
  { id: 4, term: "Myocardium", definition: "The muscular middle layer of the heart wall", category: "Cardiovascular System", categoryId: 1 },
  { id: 5, term: "Systole", definition: "The phase of the heartbeat when the heart muscle contracts", category: "Cardiovascular System", categoryId: 1 },
  { id: 6, term: "Diastole", definition: "The phase of the heartbeat when the heart muscle relaxes", category: "Cardiovascular System", categoryId: 1 },
  { id: 7, term: "Capillary", definition: "Tiny blood vessel where gas and nutrient exchange occurs", category: "Cardiovascular System", categoryId: 1 },
  { id: 8, term: "Artery", definition: "Blood vessel that carries blood away from the heart", category: "Cardiovascular System", categoryId: 1 },
  { id: 9, term: "Vein", definition: "Blood vessel that carries blood toward the heart", category: "Cardiovascular System", categoryId: 1 },
  { id: 10, term: "Cardiac Output", definition: "The amount of blood the heart pumps per minute", category: "Cardiovascular System", categoryId: 1 },
  { id: 11, term: "Pericardium", definition: "The protective sac surrounding the heart", category: "Cardiovascular System", categoryId: 1 },
  { id: 12, term: "Endocardium", definition: "The inner lining of the heart chambers", category: "Cardiovascular System", categoryId: 1 },
  { id: 13, term: "Valve", definition: "Structure that ensures one-way blood flow through the heart", category: "Cardiovascular System", categoryId: 1 },
  { id: 14, term: "Sinoatrial Node", definition: "Natural pacemaker of the heart located in the right atrium", category: "Cardiovascular System", categoryId: 1 },
  { id: 15, term: "Coronary Artery", definition: "Artery that supplies blood to the heart muscle itself", category: "Cardiovascular System", categoryId: 1 },
  { id: 16, term: "Pulmonary Circulation", definition: "Blood flow between the heart and lungs", category: "Cardiovascular System", categoryId: 1 },
  { id: 17, term: "Systemic Circulation", definition: "Blood flow between the heart and the rest of the body", category: "Cardiovascular System", categoryId: 1 },
  { id: 18, term: "Hypertension", definition: "Abnormally high blood pressure", category: "Cardiovascular System", categoryId: 1 },
  { id: 19, term: "Atherosclerosis", definition: "Hardening and narrowing of arteries due to plaque buildup", category: "Cardiovascular System", categoryId: 1 },
  { id: 20, term: "Stroke Volume", definition: "Amount of blood pumped by the left ventricle per beat", category: "Cardiovascular System", categoryId: 1 },
  { id: 21, term: "Electrocardiogram", definition: "Recording of the electrical activity of the heart", category: "Cardiovascular System", categoryId: 1 },
  { id: 22, term: "Tricuspid Valve", definition: "Valve between the right atrium and right ventricle", category: "Cardiovascular System", categoryId: 1 },
  { id: 23, term: "Mitral Valve", definition: "Valve between the left atrium and left ventricle", category: "Cardiovascular System", categoryId: 1 },
  { id: 24, term: "Angina", definition: "Chest pain caused by reduced blood flow to the heart", category: "Cardiovascular System", categoryId: 1 },
  { id: 25, term: "Arrhythmia", definition: "Irregular heart rhythm or heartbeat", category: "Cardiovascular System", categoryId: 1 },
  { id: 26, term: "Ventricular Fibrillation", definition: "Life-threatening irregular heart rhythm in the ventricles", category: "Cardiovascular System", categoryId: 1 },
  { id: 27, term: "Hemoglobin", definition: "Protein in red blood cells that carries oxygen", category: "Cardiovascular System", categoryId: 1 },
  { id: 28, term: "Plasma", definition: "Liquid component of blood that carries cells and nutrients", category: "Cardiovascular System", categoryId: 1 },
  { id: 29, term: "Platelet", definition: "Blood cell fragment involved in clotting", category: "Cardiovascular System", categoryId: 1 },
  { id: 30, term: "Vasoconstriction", definition: "Narrowing of blood vessels, increasing blood pressure", category: "Cardiovascular System", categoryId: 1 },

  // Skeletal System (30 definitions)
  { id: 31, term: "Femur", definition: "The thigh bone, the longest and strongest bone in the body", category: "Skeletal System", categoryId: 2 },
  { id: 32, term: "Tibia", definition: "The larger shin bone in the lower leg", category: "Skeletal System", categoryId: 2 },
  { id: 33, term: "Fibula", definition: "The smaller bone in the lower leg, lateral to the tibia", category: "Skeletal System", categoryId: 2 },
  { id: 34, term: "Humerus", definition: "The upper arm bone extending from shoulder to elbow", category: "Skeletal System", categoryId: 2 },
  { id: 35, term: "Radius", definition: "The lateral forearm bone on the thumb side", category: "Skeletal System", categoryId: 2 },
  { id: 36, term: "Ulna", definition: "The medial forearm bone on the pinky side", category: "Skeletal System", categoryId: 2 },
  { id: 37, term: "Vertebra", definition: "Individual bone of the spinal column", category: "Skeletal System", categoryId: 2 },
  { id: 38, term: "Pelvis", definition: "Basin-shaped structure connecting the spine to the lower limbs", category: "Skeletal System", categoryId: 2 },
  { id: 39, term: "Cranium", definition: "The skull bones that encase and protect the brain", category: "Skeletal System", categoryId: 2 },
  { id: 40, term: "Sternum", definition: "The breastbone in the center of the chest", category: "Skeletal System", categoryId: 2 },
  { id: 41, term: "Ribs", definition: "Curved bones forming the rib cage to protect vital organs", category: "Skeletal System", categoryId: 2 },
  { id: 42, term: "Scapula", definition: "The shoulder blade, a flat triangular bone", category: "Skeletal System", categoryId: 2 },
  { id: 43, term: "Clavicle", definition: "The collarbone connecting the sternum to the scapula", category: "Skeletal System", categoryId: 2 },
  { id: 44, term: "Patella", definition: "The kneecap, a small bone protecting the knee joint", category: "Skeletal System", categoryId: 2 },
  { id: 45, term: "Cartilage", definition: "Flexible connective tissue found in joints and other areas", category: "Skeletal System", categoryId: 2 },
  { id: 46, term: "Ligament", definition: "Fibrous tissue connecting bone to bone", category: "Skeletal System", categoryId: 2 },
  { id: 47, term: "Tendon", definition: "Fibrous tissue connecting muscle to bone", category: "Skeletal System", categoryId: 2 },
  { id: 48, term: "Synovial Joint", definition: "Freely movable joint containing synovial fluid", category: "Skeletal System", categoryId: 2 },
  { id: 49, term: "Bone Marrow", definition: "Soft tissue inside bones that produces blood cells", category: "Skeletal System", categoryId: 2 },
  { id: 50, term: "Compact Bone", definition: "Dense, hard outer layer of bone tissue", category: "Skeletal System", categoryId: 2 },
  { id: 51, term: "Spongy Bone", definition: "Porous, lightweight inner bone tissue", category: "Skeletal System", categoryId: 2 },
  { id: 52, term: "Osteoblast", definition: "Cell responsible for bone formation", category: "Skeletal System", categoryId: 2 },
  { id: 53, term: "Osteoclast", definition: "Cell responsible for bone resorption and remodeling", category: "Skeletal System", categoryId: 2 },
  { id: 54, term: "Osteoporosis", definition: "Condition characterized by weakened, porous bones", category: "Skeletal System", categoryId: 2 },
  { id: 55, term: "Fracture", definition: "A break or crack in a bone", category: "Skeletal System", categoryId: 2 },
  { id: 56, term: "Arthritis", definition: "Inflammation of one or more joints causing pain and stiffness", category: "Skeletal System", categoryId: 2 },
  { id: 57, term: "Spinal Disc", definition: "Cushioning pad between vertebrae in the spine", category: "Skeletal System", categoryId: 2 },
  { id: 58, term: "Mandible", definition: "The lower jawbone, the only movable skull bone", category: "Skeletal System", categoryId: 2 },
  { id: 59, term: "Cervical Vertebrae", definition: "The seven vertebrae in the neck region", category: "Skeletal System", categoryId: 2 },
  { id: 60, term: "Lumbar Vertebrae", definition: "The five vertebrae in the lower back region", category: "Skeletal System", categoryId: 2 },

  // Nervous System (30 definitions)
  { id: 61, term: "Neuron", definition: "Nerve cell that transmits electrical signals", category: "Nervous System", categoryId: 3 },
  { id: 62, term: "Synapse", definition: "Junction between two neurons where signals are transmitted", category: "Nervous System", categoryId: 3 },
  { id: 63, term: "Dendrite", definition: "Branch-like extension of a neuron that receives signals", category: "Nervous System", categoryId: 3 },
  { id: 64, term: "Axon", definition: "Long fiber that carries signals away from the neuron cell body", category: "Nervous System", categoryId: 3 },
  { id: 65, term: "Cerebrum", definition: "Largest part of the brain responsible for higher functions", category: "Nervous System", categoryId: 3 },
  { id: 66, term: "Cerebellum", definition: "Brain region that coordinates movement and balance", category: "Nervous System", categoryId: 3 },
  { id: 67, term: "Brainstem", definition: "Structure connecting the brain to the spinal cord", category: "Nervous System", categoryId: 3 },
  { id: 68, term: "Frontal Lobe", definition: "Brain region involved in reasoning, planning, and movement", category: "Nervous System", categoryId: 3 },
  { id: 69, term: "Parietal Lobe", definition: "Brain region processing sensory information", category: "Nervous System", categoryId: 3 },
  { id: 70, term: "Temporal Lobe", definition: "Brain region involved in hearing and memory", category: "Nervous System", categoryId: 3 },
  { id: 71, term: "Occipital Lobe", definition: "Brain region responsible for visual processing", category: "Nervous System", categoryId: 3 },
  { id: 72, term: "Myelin Sheath", definition: "Fatty coating that insulates axons and speeds signal transmission", category: "Nervous System", categoryId: 3 },
  { id: 73, term: "Neurotransmitter", definition: "Chemical messenger that transmits signals across synapses", category: "Nervous System", categoryId: 3 },
  { id: 74, term: "Dopamine", definition: "Neurotransmitter involved in reward, motivation, and movement", category: "Nervous System", categoryId: 3 },
  { id: 75, term: "Serotonin", definition: "Neurotransmitter that regulates mood, sleep, and appetite", category: "Nervous System", categoryId: 3 },
  { id: 76, term: "Spinal Cord", definition: "Bundle of nerves running through the vertebral column", category: "Nervous System", categoryId: 3 },
  { id: 77, term: "Reflex Arc", definition: "Neural pathway controlling an automatic response to stimulus", category: "Nervous System", categoryId: 3 },
  { id: 78, term: "Autonomic Nervous System", definition: "Part of nervous system controlling involuntary functions", category: "Nervous System", categoryId: 3 },
  { id: 79, term: "Sympathetic Nervous System", definition: "Division that prepares body for stress or emergency", category: "Nervous System", categoryId: 3 },
  { id: 80, term: "Parasympathetic Nervous System", definition: "Division that promotes rest and digestion", category: "Nervous System", categoryId: 3 },
  { id: 81, term: "Action Potential", definition: "Electrical signal traveling along a neuron", category: "Nervous System", categoryId: 3 },
  { id: 82, term: "Gray Matter", definition: "Neural tissue containing cell bodies and dendrites", category: "Nervous System", categoryId: 3 },
  { id: 83, term: "White Matter", definition: "Neural tissue consisting primarily of myelinated axons", category: "Nervous System", categoryId: 3 },
  { id: 84, term: "Meninges", definition: "Three protective membranes covering the brain and spinal cord", category: "Nervous System", categoryId: 3 },
  { id: 85, term: "Cerebrospinal Fluid", definition: "Fluid cushioning and nourishing the brain and spinal cord", category: "Nervous System", categoryId: 3 },
  { id: 86, term: "Parkinson's Disease", definition: "Degenerative disorder affecting movement and dopamine production", category: "Nervous System", categoryId: 3 },
  { id: 87, term: "Alzheimer's Disease", definition: "Progressive brain disorder causing memory loss and cognitive decline", category: "Nervous System", categoryId: 3 },
  { id: 88, term: "Epilepsy", definition: "Neurological disorder causing recurrent seizures", category: "Nervous System", categoryId: 3 },
  { id: 89, term: "Multiple Sclerosis", definition: "Autoimmune disease damaging myelin sheaths", category: "Nervous System", categoryId: 3 },
  { id: 90, term: "Hippocampus", definition: "Brain structure critical for memory formation", category: "Nervous System", categoryId: 3 },

  // Visual System (30 definitions)
  { id: 91, term: "Cornea", definition: "Clear outer layer of the eye that focuses light", category: "Visual System", categoryId: 4 },
  { id: 92, term: "Iris", definition: "Colored part of the eye that controls pupil size", category: "Visual System", categoryId: 4 },
  { id: 93, term: "Pupil", definition: "Opening in the center of the iris that allows light to enter", category: "Visual System", categoryId: 4 },
  { id: 94, term: "Lens", definition: "Transparent structure that focuses light onto the retina", category: "Visual System", categoryId: 4 },
  { id: 95, term: "Retina", definition: "Light-sensitive layer at the back of the eye", category: "Visual System", categoryId: 4 },
  { id: 96, term: "Photoreceptor", definition: "Cell in the retina that detects light", category: "Visual System", categoryId: 4 },
  { id: 97, term: "Rods", definition: "Photoreceptors responsible for low-light and peripheral vision", category: "Visual System", categoryId: 4 },
  { id: 98, term: "Cones", definition: "Photoreceptors responsible for color vision and detail", category: "Visual System", categoryId: 4 },
  { id: 99, term: "Macula", definition: "Central area of the retina responsible for sharp vision", category: "Visual System", categoryId: 4 },
  { id: 100, term: "Fovea", definition: "Small pit in the macula with the highest visual acuity", category: "Visual System", categoryId: 4 },
  { id: 101, term: "Optic Nerve", definition: "Nerve that transmits visual information from eye to brain", category: "Visual System", categoryId: 4 },
  { id: 102, term: "Vitreous Humor", definition: "Gel-like substance filling the eye behind the lens", category: "Visual System", categoryId: 4 },
  { id: 103, term: "Aqueous Humor", definition: "Clear fluid in the front part of the eye", category: "Visual System", categoryId: 4 },
  { id: 104, term: "Sclera", definition: "White outer layer of the eyeball", category: "Visual System", categoryId: 4 },
  { id: 105, term: "Choroid", definition: "Vascular layer between the retina and sclera", category: "Visual System", categoryId: 4 },
  { id: 106, term: "Accommodation", definition: "Eye's ability to change focus from distant to near objects", category: "Visual System", categoryId: 4 },
  { id: 107, term: "Myopia", definition: "Nearsightedness, difficulty seeing distant objects clearly", category: "Visual System", categoryId: 4 },
  { id: 108, term: "Hyperopia", definition: "Farsightedness, difficulty seeing near objects clearly", category: "Visual System", categoryId: 4 },
  { id: 109, term: "Astigmatism", definition: "Irregular curvature of the cornea causing blurred vision", category: "Visual System", categoryId: 4 },
  { id: 110, term: "Cataract", definition: "Clouding of the eye's lens causing vision impairment", category: "Visual System", categoryId: 4 },
  { id: 111, term: "Glaucoma", definition: "Eye disease causing optic nerve damage from increased pressure", category: "Visual System", categoryId: 4 },
  { id: 112, term: "Macular Degeneration", definition: "Progressive damage to the macula affecting central vision", category: "Visual System", categoryId: 4 },
  { id: 113, term: "Visual Cortex", definition: "Brain region that processes visual information", category: "Visual System", categoryId: 4 },
  { id: 114, term: "Blind Spot", definition: "Area of the retina where the optic nerve exits, lacking photoreceptors", category: "Visual System", categoryId: 4 },
  { id: 115, term: "Binocular Vision", definition: "Using both eyes together to perceive depth", category: "Visual System", categoryId: 4 },
  { id: 116, term: "Depth Perception", definition: "Ability to judge distance and three-dimensional space", category: "Visual System", categoryId: 4 },
  { id: 117, term: "Color Blindness", definition: "Inability to distinguish certain colors, often red-green", category: "Visual System", categoryId: 4 },
  { id: 118, term: "Presbyopia", definition: "Age-related loss of ability to focus on near objects", category: "Visual System", categoryId: 4 },
  { id: 119, term: "Conjunctiva", definition: "Thin membrane covering the white of the eye and inner eyelids", category: "Visual System", categoryId: 4 },
  { id: 120, term: "Lacrimal Gland", definition: "Gland that produces tears to lubricate the eye", category: "Visual System", categoryId: 4 },

  // Auditory System (30 definitions)
  { id: 121, term: "Outer Ear", definition: "External portion of the ear including the pinna and ear canal", category: "Auditory System", categoryId: 5 },
  { id: 122, term: "Pinna", definition: "Visible external part of the ear that collects sound", category: "Auditory System", categoryId: 5 },
  { id: 123, term: "Ear Canal", definition: "Tube leading from outer ear to the eardrum", category: "Auditory System", categoryId: 5 },
  { id: 124, term: "Tympanic Membrane", definition: "Eardrum that vibrates in response to sound waves", category: "Auditory System", categoryId: 5 },
  { id: 125, term: "Middle Ear", definition: "Air-filled cavity containing the ossicles", category: "Auditory System", categoryId: 5 },
  { id: 126, term: "Ossicles", definition: "Three tiny bones (malleus, incus, stapes) that amplify sound", category: "Auditory System", categoryId: 5 },
  { id: 127, term: "Malleus", definition: "Hammer-shaped bone, first of the three ossicles", category: "Auditory System", categoryId: 5 },
  { id: 128, term: "Incus", definition: "Anvil-shaped bone, middle ossicle", category: "Auditory System", categoryId: 5 },
  { id: 129, term: "Stapes", definition: "Stirrup-shaped bone, smallest bone in the human body", category: "Auditory System", categoryId: 5 },
  { id: 130, term: "Eustachian Tube", definition: "Tube connecting middle ear to throat, equalizing pressure", category: "Auditory System", categoryId: 5 },
  { id: 131, term: "Inner Ear", definition: "Contains the cochlea and vestibular system", category: "Auditory System", categoryId: 5 },
  { id: 132, term: "Cochlea", definition: "Spiral-shaped structure converting sound vibrations to nerve signals", category: "Auditory System", categoryId: 5 },
  { id: 133, term: "Hair Cells", definition: "Sensory cells in the cochlea that detect sound vibrations", category: "Auditory System", categoryId: 5 },
  { id: 134, term: "Organ of Corti", definition: "Structure in the cochlea containing hair cells", category: "Auditory System", categoryId: 5 },
  { id: 135, term: "Auditory Nerve", definition: "Nerve transmitting sound information from cochlea to brain", category: "Auditory System", categoryId: 5 },
  { id: 136, term: "Vestibular System", definition: "Inner ear structures responsible for balance", category: "Auditory System", categoryId: 5 },
  { id: 137, term: "Semicircular Canals", definition: "Three fluid-filled loops detecting rotational movement", category: "Auditory System", categoryId: 5 },
  { id: 138, term: "Utricle", definition: "Structure detecting linear acceleration and head position", category: "Auditory System", categoryId: 5 },
  { id: 139, term: "Saccule", definition: "Structure detecting vertical movement and gravity", category: "Auditory System", categoryId: 5 },
  { id: 140, term: "Frequency", definition: "Rate of sound wave vibration, perceived as pitch", category: "Auditory System", categoryId: 5 },
  { id: 141, term: "Amplitude", definition: "Height of sound wave, perceived as loudness", category: "Auditory System", categoryId: 5 },
  { id: 142, term: "Decibel", definition: "Unit measuring sound intensity or loudness", category: "Auditory System", categoryId: 5 },
  { id: 143, term: "Hearing Loss", definition: "Reduced ability to hear sounds in one or both ears", category: "Auditory System", categoryId: 5 },
  { id: 144, term: "Conductive Hearing Loss", definition: "Hearing loss due to problems in outer or middle ear", category: "Auditory System", categoryId: 5 },
  { id: 145, term: "Sensorineural Hearing Loss", definition: "Hearing loss due to inner ear or auditory nerve damage", category: "Auditory System", categoryId: 5 },
  { id: 146, term: "Tinnitus", definition: "Perception of ringing or noise in the ears without external source", category: "Auditory System", categoryId: 5 },
  { id: 147, term: "Vertigo", definition: "Sensation of spinning or loss of balance", category: "Auditory System", categoryId: 5 },
  { id: 148, term: "Meniere's Disease", definition: "Inner ear disorder causing vertigo, tinnitus, and hearing loss", category: "Auditory System", categoryId: 5 },
  { id: 149, term: "Auditory Cortex", definition: "Brain region that processes sound information", category: "Auditory System", categoryId: 5 },
  { id: 150, term: "Sound Localization", definition: "Ability to identify the direction and distance of sound sources", category: "Auditory System", categoryId: 5 },

  // Respiratory System (30 definitions)
  { id: 151, term: "Trachea", definition: "Windpipe that connects the throat to the bronchi", category: "Respiratory System", categoryId: 6 },
  { id: 152, term: "Bronchi", definition: "Two main branches of the trachea leading to each lung", category: "Respiratory System", categoryId: 6 },
  { id: 153, term: "Bronchioles", definition: "Small airways branching from bronchi to alveoli", category: "Respiratory System", categoryId: 6 },
  { id: 154, term: "Alveoli", definition: "Tiny air sacs where gas exchange occurs", category: "Respiratory System", categoryId: 6 },
  { id: 155, term: "Diaphragm", definition: "Dome-shaped muscle that controls breathing", category: "Respiratory System", categoryId: 6 },
  { id: 156, term: "Pleura", definition: "Double membrane surrounding the lungs", category: "Respiratory System", categoryId: 6 },
  { id: 157, term: "Larynx", definition: "Voice box containing the vocal cords", category: "Respiratory System", categoryId: 6 },
  { id: 158, term: "Pharynx", definition: "Throat area connecting nasal cavity to larynx and esophagus", category: "Respiratory System", categoryId: 6 },
  { id: 159, term: "Epiglottis", definition: "Flap of tissue preventing food from entering airways", category: "Respiratory System", categoryId: 6 },
  { id: 160, term: "Nasal Cavity", definition: "Space inside the nose that filters and warms air", category: "Respiratory System", categoryId: 6 },
  { id: 161, term: "Inspiration", definition: "The process of breathing air into the lungs", category: "Respiratory System", categoryId: 6 },
  { id: 162, term: "Expiration", definition: "The process of breathing air out of the lungs", category: "Respiratory System", categoryId: 6 },
  { id: 163, term: "Vital Capacity", definition: "Maximum amount of air that can be exhaled after full inhalation", category: "Respiratory System", categoryId: 6 },
  { id: 164, term: "Tidal Volume", definition: "Amount of air inhaled or exhaled during normal breathing", category: "Respiratory System", categoryId: 6 },
  { id: 165, term: "Oxygen", definition: "Gas essential for cellular respiration and energy production", category: "Respiratory System", categoryId: 6 },
  { id: 166, term: "Carbon Dioxide", definition: "Waste gas produced by cellular metabolism", category: "Respiratory System", categoryId: 6 },
  { id: 167, term: "Diffusion", definition: "Movement of gases from high to low concentration", category: "Respiratory System", categoryId: 6 },
  { id: 168, term: "Pulmonary Capillaries", definition: "Tiny blood vessels surrounding alveoli for gas exchange", category: "Respiratory System", categoryId: 6 },
  { id: 169, term: "Surfactant", definition: "Substance reducing surface tension in alveoli", category: "Respiratory System", categoryId: 6 },
  { id: 170, term: "Asthma", definition: "Chronic condition causing airway inflammation and narrowing", category: "Respiratory System", categoryId: 6 },
  { id: 171, term: "Pneumonia", definition: "Infection causing inflammation of the lung's air sacs", category: "Respiratory System", categoryId: 6 },
  { id: 172, term: "COPD", definition: "Chronic Obstructive Pulmonary Disease, progressive lung disease", category: "Respiratory System", categoryId: 6 },
  { id: 173, term: "Emphysema", definition: "Condition damaging alveoli and reducing gas exchange", category: "Respiratory System", categoryId: 6 },
  { id: 174, term: "Bronchitis", definition: "Inflammation of the bronchial tubes", category: "Respiratory System", categoryId: 6 },
  { id: 175, term: "Cilia", definition: "Tiny hair-like structures that sweep mucus and debris from airways", category: "Respiratory System", categoryId: 6 },
  { id: 176, term: "Mucus", definition: "Sticky substance trapping particles and pathogens in airways", category: "Respiratory System", categoryId: 6 },
  { id: 177, term: "Respiratory Rate", definition: "Number of breaths taken per minute", category: "Respiratory System", categoryId: 6 },
  { id: 178, term: "Hypoxia", definition: "Inadequate oxygen supply to tissues", category: "Respiratory System", categoryId: 6 },
  { id: 179, term: "Spirometry", definition: "Test measuring lung capacity and airflow", category: "Respiratory System", categoryId: 6 },
  { id: 180, term: "Pulmonary Edema", definition: "Fluid accumulation in the lungs", category: "Respiratory System", categoryId: 6 },
]

